[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
ffi = true
fuzz = { runs = 256 }
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
out = "out"
solc = "0.8.17"
src = "src"
test = "test"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config